import type { AppState, Participant, Ticket } from './types';

const sprintId = 'sprint-ax-hr-1';

const participants: Participant[] = [
  {
    id: 'P-0',
    displayName: '문턱장',
    role: '운영자 / HR AX 컨설턴트 훈련자',
    surveyRawText: '',
    problemStatement: 'AX x HR 실천 모임 운영 과정을 AI로 보조하고, 컨설턴트 훈련 기록으로 남긴다.',
    problemType: '운영 / 컨설턴트 훈련',
    desiredOutcome: '참가자 문제를 듣고 구조화하고 다음 액션으로 전환하는 운영 시스템을 만든다.',
    aiLeveragePoint: '설문 분석, 후속 질문 생성, 회고 분석, 티켓 생성, 방법론 정리',
    outputCandidate: 'AX x HR Sprint OS 운영 리포트와 방법론 초안',
    successCriteria: '3회 이상 회고를 남기고 Humanistic HR AX Consulting Method v0.1을 만든다.',
    leaderHighRelevance: '참가자 문제 중 리더십 대화 관련 주제를 시나리오 후보로 전환',
    consultingTrainingPoint: '문제 청취, 재정의, AI 적용 가능성 판단, 범위 축소 훈련',
    analysisMarkdown: '',
    publicSummary: '운영자 프로젝트: 모임 운영 과정을 AI로 보조하고 컨설팅 방법론으로 정리한다.',
    currentProgress: 'MVP 운영툴 구축 중',
    nextAction: '사전 설문 발송 및 참가자 응답 수집',
    participantUpdate: '',
    lifecycle: {
      ownProblem: '',
      understandSystem: '',
      smallProject: '',
      shareReflectSystemize: '',
      goalConversation: '',
      strategyConversation: '',
      retrospectiveConversation: '',
      fieldTest: '',
      caseNote: '',
    },
    facilitatorNote: {
      diagnosis: '',
      followUpQuestions: '',
      scopeReduction: '',
      missedQuestions: '',
      interventionLog: '',
    },
  },
  ...['P-1', 'P-2', 'P-3'].map((id) => ({
    id,
    displayName: id,
    role: '',
    surveyRawText: '',
    problemStatement: '',
    problemType: '',
    desiredOutcome: '',
    aiLeveragePoint: '',
    outputCandidate: '',
    successCriteria: '',
    leaderHighRelevance: '',
    consultingTrainingPoint: '',
    analysisMarkdown: '',
    publicSummary: '',
    currentProgress: '',
    nextAction: '',
    participantUpdate: '',
    lifecycle: {
      ownProblem: '',
      understandSystem: '',
      smallProject: '',
      shareReflectSystemize: '',
      goalConversation: '',
      strategyConversation: '',
      retrospectiveConversation: '',
      fieldTest: '',
      caseNote: '',
    },
    facilitatorNote: {
      diagnosis: '',
      followUpQuestions: '',
      scopeReduction: '',
      missedQuestions: '',
      interventionLog: '',
    },
  })),
];

const tickets: Ticket[] = [
  {
    id: 'ticket-prep-1',
    sprintId,
    stage: 'prep',
    title: '참가자 3명에게 사전 설문 발송',
    description: '11-pre-kickoff-survey.md의 안내 메시지와 Google Form 링크를 참가자에게 보낸다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-prep-2',
    sprintId,
    stage: 'prep',
    title: '설문 응답 수집 후 참가자별 후속 질문 3개 준비',
    description: '응답을 Participants 탭에 붙여 넣고 Analysis 탭에서 설문 분석 프롬프트를 생성한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week1-1',
    sprintId,
    stage: 'week1',
    title: '1주차 문제 정의 모임 진행',
    description: '4명 모두 문제 정의 1문장, 결과물 형태 1개, 성공 기준 1개를 확정한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week1-2',
    sprintId,
    stage: 'week1',
    title: '1주차 후 Consultant Reflection 작성',
    description: '모임 직후 20분 동안 운영자 회고를 작성하고 Reflection 탭에 저장한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
];

export const initialState: AppState = {
  sprint: {
    id: sprintId,
    title: 'AX x HR 실천 모임 1기',
    startDate: '',
    endDate: '',
    purpose: '문턱장이 HR AX 컨설턴트로 훈련되고 참가자들이 현업 문제를 AI로 작게 실험하는 3주 스프린트',
    currentStage: 'prep',
    notes: '1차 목적은 컨설턴트 훈련, 2차 목적은 참가자 문제 해결, 3차 목적은 Humanistic 방법론 축적이다.',
  },
  participants,
  tickets,
  analyses: [],
  reflections: [],
  methodLibrary: {
    philosophy: '조직은 우리답게, 개인은 자기답게 일해야 한다. 3개월 목표는 고객에게 자신이 생각하는 문제를 AI를 활용해 해결해보는 경험을 선물하는 것이다.',
    methodName: 'OURS Method',
    principles: 'O — Own the Problem / U — Understand the System / R — Run a Small Project / S — Share, Reflect, Systemize',
    effectiveQuestions: '',
    aiUsePatterns: '',
    scopeReductionPatterns: '',
    dialoguePatterns: '목표 설정 대화, 전략 수립 대화, 실행 점검 대화, 회고 대화',
    cohortRetrospective: '',
  },
};
