import type { AppState, Participant, Ticket } from './types';

const sprintId = 'sprint-ax-hr-1';

const participants: Participant[] = [
  {
    id: 'P-0',
    displayName: '문턱장',
    role: '운영자 / HR AX 컨설턴트 훈련자',
    surveyRawText: '',
    problemStatement: 'AX x HR 실천 모임 운영 과정을 AI로 보조하고, 컨설턴트 훈련 기록으로 남긴다.',
    problemType: '운영 / 컨설턴트 훈련',
    desiredOutcome: '참가자 문제를 듣고 구조화하고 다음 액션으로 전환하는 운영 시스템을 만든다.',
    aiLeveragePoint: '설문 분석, 후속 질문 생성, 회고 분석, 티켓 생성, 방법론 정리',
    outputCandidate: 'AX x HR Sprint OS 운영 리포트와 방법론 초안',
    successCriteria: '3회 이상 회고를 남기고 Humanistic HR AX Consulting Method v0.1을 만든다.',
    leaderHighRelevance: '참가자 문제 중 리더십 대화 관련 주제를 시나리오 후보로 전환',
    consultingTrainingPoint: '문제 청취, 재정의, AI 적용 가능성 판단, 범위 축소 훈련',
    analysisMarkdown: '',
    publicSummary: '운영자 프로젝트: 모임 운영 과정을 AI로 보조하고 컨설팅 방법론으로 정리한다.',
    currentProgress: 'MVP 운영툴 구축 중',
    nextAction: '사전 설문 발송 및 참가자 응답 수집',
    participantUpdate: '',
    lifecycle: {
      ownProblem: '',
      understandSystem: '',
      smallProject: '',
      shareReflectSystemize: '',
      goalConversation: '',
      strategyConversation: '',
      retrospectiveConversation: '',
      fieldTest: '',
      caseNote: '',
    },
    facilitatorNote: {
      diagnosis: '',
      followUpQuestions: '',
      scopeReduction: '',
      missedQuestions: '',
      interventionLog: '',
    },
  },
  ...['P-1', 'P-2', 'P-3'].map((id) => ({
    id,
    displayName: id,
    role: '',
    surveyRawText: '',
    problemStatement: '',
    problemType: '',
    desiredOutcome: '',
    aiLeveragePoint: '',
    outputCandidate: '',
    successCriteria: '',
    leaderHighRelevance: '',
    consultingTrainingPoint: '',
    analysisMarkdown: '',
    publicSummary: '',
    currentProgress: '',
    nextAction: '',
    participantUpdate: '',
    lifecycle: {
      ownProblem: '',
      understandSystem: '',
      smallProject: '',
      shareReflectSystemize: '',
      goalConversation: '',
      strategyConversation: '',
      retrospectiveConversation: '',
      fieldTest: '',
      caseNote: '',
    },
    facilitatorNote: {
      diagnosis: '',
      followUpQuestions: '',
      scopeReduction: '',
      missedQuestions: '',
      interventionLog: '',
    },
  })),
];

const tickets: Ticket[] = [
  {
    id: 'ticket-prep-1',
    sprintId,
    stage: 'prep',
    title: 'Google Form 사전 설문 만들기',
    description: '11-pre-kickoff-survey.md 내용을 Google Form으로 옮긴다. 제목, 설명, Q1~Q12, 응답 후 안내문까지 포함한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-prep-2',
    sprintId,
    stage: 'prep',
    title: '참가자 3명에게 사전 설문 발송',
    description: '02-kickoff-message-script.md의 톤을 참고해 참가자에게 설문 링크와 응답 마감 시간을 보낸다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-prep-3',
    sprintId,
    stage: 'prep',
    title: 'Sprint OS 배포 URL과 화면 모드 확인',
    description: '참가자용 ?view=public, 운영자용 ?view=admin 링크가 정상 동작하는지 확인한다. 현재 localStorage 기반이라 공동 편집이 아니라 화면 공유 중심으로 운영한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-prep-4',
    sprintId,
    stage: 'prep',
    title: '설문 응답을 참가자 카드에 입력',
    description: 'P-1~P-3의 설문 원문, 문제 후보, 기대 결과, AI 활용 지점, 다음 액션을 Participants/Data 탭에 입력한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-prep-5',
    sprintId,
    stage: 'prep',
    title: '참가자별 후속 질문 3개 준비',
    description: 'Analysis 탭에서 로키 분석 프롬프트를 만들고 각 참가자에게 물어볼 후속 질문 3개를 정리한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'medium',
    generatedBy: 'template',
  },
  {
    id: 'ticket-prep-6',
    sprintId,
    stage: 'prep',
    title: '첫 모임 진행안과 화면 공유 리허설',
    description: '00 운영 인덱스, 10 실행 플랜, 17 Sprint OS 운영 매뉴얼을 열어두고 공유룸/티켓/프로젝트 랩 화면 전환을 한 번 테스트한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'medium',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week1-1',
    sprintId,
    stage: 'week1',
    title: '1주차 오프닝: 모임 목적과 OURS Method 설명',
    description: 'AI 교육이 아니라 자기 문제를 AI와 함께 작은 프로젝트로 바꾸는 실천 모임임을 설명한다. O/U/R/S 흐름을 공유한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week1-2',
    sprintId,
    stage: 'week1',
    title: '참가자별 문제 정의 1문장 확정',
    description: '각 참가자의 문제를 "누가 / 어떤 상황에서 / 무엇이 막혀서 / 어떤 변화가 필요한가" 형태로 정리한다.',
    owner: 'participant',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week1-3',
    sprintId,
    stage: 'week1',
    title: 'v0.1 결과물 후보와 성공 기준 정하기',
    description: '참가자별로 3주 안에 만들 수 있는 작은 결과물 1개와 현업에서 확인할 성공 기준 1개를 정한다.',
    owner: 'participant',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week1-4',
    sprintId,
    stage: 'week1',
    title: '1주차 후 운영자 회고 작성',
    description: 'Reflection 탭에 잘 물어본 질문, 놓친 질문, 범위 축소 패턴, 다음 주 개입 포인트를 남긴다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week1-5',
    sprintId,
    stage: 'week1',
    title: 'Week 1 산출물: Problem Statement 정리',
    description: '각 참가자의 문제 정의, 이해관계자, 반복되는 상황, AI 적용 가능 지점을 Project Lab에 정리한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'medium',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week2-1',
    sprintId,
    stage: 'week2',
    title: '2주차 시작 전 v0.1 제작 범위 재확인',
    description: '각 프로젝트가 너무 크면 줄인다. 문서, 체크리스트, 프롬프트, 대화 스크립트, 간단한 자동화 중 하나로 좁힌다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week2-2',
    sprintId,
    stage: 'week2',
    title: '참가자별 v0.1 결과물 만들기',
    description: 'AI를 실행 파트너로 써서 실제 업무에 한 번 써볼 수 있는 결과물 초안을 만든다.',
    owner: 'participant',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week2-3',
    sprintId,
    stage: 'week2',
    title: '동료 피드백과 운영자 피드백 반영',
    description: '각 결과물에 대해 이해 가능성, 현업 적용성, 너무 큰 범위 여부, 다음 실험 가능성을 기준으로 피드백한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'medium',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week2-4',
    sprintId,
    stage: 'week2',
    title: 'Week 2 산출물: v0.1 Output 저장',
    description: '각 참가자의 v0.1 결과물 링크/내용/사용 방법을 Sprint OS와 Obsidian에 남긴다.',
    owner: 'operator',
    status: 'todo',
    priority: 'medium',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week2-5',
    sprintId,
    stage: 'week2',
    title: '2주차 후 운영자 회고 작성',
    description: '어떤 질문이 결과물 제작을 도왔는지, 어떤 범위 축소가 효과적이었는지, Humanistic 방법론 후보를 기록한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'medium',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week3-1',
    sprintId,
    stage: 'week3',
    title: '현업 테스트 계획 확정',
    description: '각 참가자가 v0.1 결과물을 어디서, 누구에게, 어떤 방식으로 한 번 써볼지 정한다.',
    owner: 'participant',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week3-2',
    sprintId,
    stage: 'week3',
    title: '현업에서 v0.1 한 번 사용하기',
    description: '완벽한 적용이 아니라 한 번 써보고 반응, 막힌 점, 다음 개선점을 기록한다.',
    owner: 'participant',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week3-3',
    sprintId,
    stage: 'week3',
    title: 'Before/After Case Note 작성',
    description: '각 참가자별로 시작 전 문제, 만든 결과물, 현업 테스트 반응, 배운 점을 익명 케이스 노트로 정리한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week3-4',
    sprintId,
    stage: 'week3',
    title: '3주차 회고 대화 진행',
    description: '무엇이 실제로 도움이 됐는지, AI가 어디서 증폭 장치였는지, 다음에 반복할 운영 패턴이 무엇인지 묻는다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-week3-5',
    sprintId,
    stage: 'week3',
    title: 'Week 3 산출물: Case Note와 회고 저장',
    description: 'Project Lab, Reflection, Export 탭을 활용해 참가자별 케이스와 운영자 회고를 Obsidian으로 옮길 수 있게 정리한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'medium',
    generatedBy: 'template',
  },
  {
    id: 'ticket-wrapup-1',
    sprintId,
    stage: 'wrapup',
    title: 'Humanistic 방법론 v0.1 업데이트',
    description: '1기에서 반복적으로 효과가 있었던 질문, AI 활용 패턴, 범위 축소 패턴을 Method Library에 반영한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-wrapup-2',
    sprintId,
    stage: 'wrapup',
    title: '1기 실천 기록 작성',
    description: '공개 가능한 형태로 "3주 동안 각자의 HR 문제를 AI와 함께 작은 프로젝트로 바꿔본 기록"을 작성한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'high',
    generatedBy: 'template',
  },
  {
    id: 'ticket-wrapup-3',
    sprintId,
    stage: 'wrapup',
    title: '2기/기업 워크숍/컨설팅 연결 판단',
    description: '1기 결과를 보고 2기 모집, 기업 내부 워크숍, Leader’s High 연결, Humanistic 컨설팅 상품화 중 다음 선택지를 결정한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'medium',
    generatedBy: 'template',
  },
  {
    id: 'ticket-wrapup-4',
    sprintId,
    stage: 'wrapup',
    title: 'Sprint OS 개선 요청 목록 만들기',
    description: '1기 운영 중 불편했던 점을 모아 클라우드 DB, 로그인, 권한, 공동 편집, 자동 분석 등 다음 개발 backlog로 전환한다.',
    owner: 'operator',
    status: 'todo',
    priority: 'medium',
    generatedBy: 'template',
  },
];

export const initialState: AppState = {
  sprint: {
    id: sprintId,
    title: 'AX x HR 실천 모임 1기',
    startDate: '',
    endDate: '',
    purpose: '문턱장이 HR AX 컨설턴트로 훈련되고 참가자들이 현업 문제를 AI로 작게 실험하는 3주 스프린트',
    currentStage: 'prep',
    notes: '1차 목적은 컨설턴트 훈련, 2차 목적은 참가자 문제 해결, 3차 목적은 Humanistic 방법론 축적이다.',
  },
  participants,
  tickets,
  analyses: [],
  reflections: [],
  methodLibrary: {
    philosophy: '조직은 우리답게, 개인은 자기답게 일해야 한다. 3개월 목표는 고객에게 자신이 생각하는 문제를 AI를 활용해 해결해보는 경험을 선물하는 것이다.',
    methodName: 'OURS Method',
    principles: 'O — Own the Problem / U — Understand the System / R — Run a Small Project / S — Share, Reflect, Systemize',
    effectiveQuestions: '',
    aiUsePatterns: '',
    scopeReductionPatterns: '',
    dialoguePatterns: '목표 설정 대화, 전략 수립 대화, 실행 점검 대화, 회고 대화',
    cohortRetrospective: '',
  },
};
